params:
  - group: Styles
    items:
      - key: bgColor
        name: "Background Color"
        type: string
        ui: color-picker
        defaultValue: "#FFFFFF"
      - key: titleColor
        name: "Title Color"
        type: string
        ui: color-picker
        defaultValue: "#000000"
  - group: Parameters
    items:
      - key: title
        name: Title
        type: string
        ui: input
        defaultValue: "App Name"