params:
  - group: Parameters
    items:
      - key: layout
        name: Layout
        type: string
        ui: select
        options:
          - header-sidebar-content
          - header-content
          - header-content-footer
          - header-sidebar-content-footer
        defaultValue: header-sidebar-content
      - key: backgroundColor
        name: Background Color
        type: string
        ui: color-picker
        defaultValue: "#FFFFFF"
events:
  - key: onLoad
    name: onLoad